### ISSUE TITLE
recording several girls at the same time

### ISSUE THREAD

**Issue by dgfhfjkde** [KFERMercer/chaturbate-grabber#16]
how to implement recording of several girls at the same time? The only thing that came to my mind was to make an additional script in which several commands are launched.
like this:

`
#!/bin/bash

/root/chaturbate-grabber/ctbcap -f /sftp/backup/recordurbate/ germaine_jones &
/root/chaturbate-grabber/ctbcap -f /sftp/backup/recordurbate/ artease &
/root/chaturbate-grabber/ctbcap -f /sftp/backup/recordurbate/ sweet_ary 

`
Is there another way to do this?

And how to properly terminate all processes? The kill command does not work properly, the process terminates, but recording and saving still occurs, I have to reboot the server.

**Comment by KFERMercer** [comment]
Just [Using Docker](https://github.com/KFERMercer/chaturbate-grabber?tab=readme-ov-file#docker-container-recommend). 

[`docker compose`](https://github.com/KFERMercer/chaturbate-grabber/blob/master/docker-compose.yml.sample) is perfect way for monitoring multiple girls at once.

If you don't have docker available for your platform, use `screen`.
