### ISSUE TITLE
Enter or check the network incorrectly (404).

### ISSUE THREAD

**Issue by yoy123** [KFERMercer/chaturbate-grabber#2]
ctbcap fails every time. I removed the exit 0 after the Internet check code and it got closer but noticed it wasn't fetching the exact web address from highwebmedia. 

Example: Your code was coming up with this:
https://edge123.stream.highwebmedia.com/live-edge/amlst:Lindamei-sd-cb53d31a4d82ae1bc79c365f52229439f69812c709d57a813a88584669219bf1_trns_h264/playlist.m3u8

When it shoulda been this:https://edge172.stream.highwebmedia.com/live-edge/amlst:Lindamei-sd-cb53d31a4d82ae1bc79c365f52229439f69812c709d57a813a88584669219bf1_trns_h264/chunklist_w57395915_b5128000_t64RlBTOjMwLjA=.m3u8

**Comment by KFERMercer** [comment]
> I removed the exit 0 after the Internet check code

↑ don't do this. it breaks the logic of the code

as for your problem, this is a logic loophole in the program. for some reason, it can only recognize all lowercase input. I will take the time to fix it.

**Comment by KFERMercer** [comment]
https://github.com/KFERMercer/chaturbate-grabber/commit/6aa1799d18feedf110e886456c8cc69deea7f1ed fixed.
