### ISSUE TITLE
Error in the pull function

### ISSUE THREAD

**Issue by december50106** [KFERMercer/chaturbate-grabber#3]
It was normal for me to record the first few times
But it broke after this

[tls @ 0x7fffd9312dc0] Error in the pull function.
[hls @ 0x7fffd9036440] skipping 1 segments ahead, expired from playlists
[tls @ 0x7fffd9312dc0] The specified session has been invalidated for some reason.
[hls @ 0x7fffd9036440] keepalive request failed for 'https://edge284.stream.highwebmedia.com/live-edge/amlst:elisa_oliver-sd-0752a5f4fe4dc89b79a47f2da110af8dbcb1fc3fb314d9d24b76050f9ec3b132_trns_h264/media_w1504396748_b5128000_t64RlBTOjMwLjA=_5372.ts' when opening url, retrying with new connection: Input/output error

Hope to help me answer
thank you

**Comment by KFERMercer** [comment]
￼￼￼Connect broken￼.

Please make sure the model￼ is streaming￼.

**Comment by december50106** [comment]
> ￼￼￼Connect broken￼.
> 
> Please make sure the girl￼(or else) is still streaming￼.

yes ,the girl still streaming 
so I can't understand how this happened

**Comment by KFERMercer** [comment]
最好不要用ctrl z, 正常来说, ffmpeg 在收到 kill 信号后还会有其他处理. ctrl z 则会暴力切断进程.

1. 检查梯子丢包率
2. 检查磁盘剩余空间
3. 如果在报错信息后正常转入监控程序, 则无需处理
4. 如果监控程序卡在此报错信息, 则等再复现时马上检查主播的在线状态, 然后把结果反馈给我

正常来说, ctbcap 会在连接断开后短暂等待三分钟然后自行重新连接, 请自查有没有输出
```shell
录制中断, 休眠三分钟后重连...
```

**Comment by KFERMercer** [comment]
奇技淫巧: 

自行测试`edge<数字>.stream.highwebmedia.com`的服务器地址, 有些节点在中国大陆也可以流畅访问.

然后使用 `ctbcap <streamer> <数字>`配合梯子软件黑白名单即可实现高速流畅直连拉流

**Comment by december50106** [comment]
[20211117-221325] 开始录播...
[tls @ 0x7fffc56a2f80] Error in the pull function.
[hls @ 0x7fffc53ce440] skipping 1 segments ahead, expired from playlists
[tls @ 0x7fffc56a2f80] The specified session has been invalidated for some reason.
[hls @ 0x7fffc53ce440] keepalive request failed for 'https://edge281.stream.highwebmedia.com/live-edge/amlst:grettabenett-sd-cee28f684c6ae00bc31c053d29db8b3d492314d19d437f23bb8c52e99302e16a_trns_h264/media_w285279153_b5128000_t64RlBTOjMwLjA=_2823.ts' when opening url, retrying with new connection: Input/output error
[mpegts @ 0x7fffc56a4c40] PES packet size mismatch
[tls @ 0x7fffc56cd7c0] Error in the pull function.
[tls @ 0x7fffc56cd7c0] The specified session has been invalidated for some reason.
[hls @ 0x7fffc53ce440] keepalive request failed for 'https://edge281.stream.highwebmedia.com/live-edge/amlst:grettabenett-sd-cee28f684c6ae00bc31c053d29db8b3d492314d19d437f23bb8c52e99302e16a_trns_h264/media_w285279153_b5128000_t64RlBTOjMwLjA=_2824.ts' when opening url, retrying with new connection: Input/output error
[mpegts @ 0x7fffc56a4c40] PES packet size mismatch
[tls @ 0x7fffc53956c0] Error in the pull function.
[tls @ 0x7fffc53956c0] The specified session has been invalidated for some reason.
[hls @ 0x7fffc53ce440] keepalive request failed for 'https://edge281.stream.highwebmedia.com/live-edge/amlst:grettabenett-sd-cee28f684c6ae00bc31c053d29db8b3d492314d19d437f23bb8c52e99302e16a_trns_h264/media_w285279153_b5128000_t64RlBTOjMwLjA=_2825.ts' when opening url, retrying with new connection: Input/output error
[mpegts @ 0x7fffc56a4c40] PES packet size mismatch
[tls @ 0x7fffc56c6c00] Error in the pull function.
[tls @ 0x7fffc56c6c00] The specified session has been invalidated for some reason.
[hls @ 0x7fffc53ce440] keepalive request failed for 'https://edge281.stream.highwebmedia.com/live-edge/amlst:grettabenett-sd-cee28f684c6ae00bc31c053d29db8b3d492314d19d437f23bb8c52e99302e16a_trns_h264/media_w285279153_b5128000_t64RlBTOjMwLjA=_2826.ts' when opening url, retrying with new connection: Input/output error
[mpegts @ 0x7fffc56a4c40] PES packet size mismatch
[tls @ 0x7fffc59b6740] Error in the pull function.
[tls @ 0x7fffc59b6740] The specified session has been invalidated for some reason.
[hls @ 0x7fffc53ce440] keepalive request failed for 'https://edge281.stream.highwebmedia.com/live-edge/amlst:grettabenett-sd-cee28f684c6ae00bc31c053d29db8b3d492314d19d437f23bb8c52e99302e16a_trns_h264/media_w285279153_b5128000_t64RlBTOjMwLjA=_2827.ts' when opening url, retrying with new connection: Input/output error
[mpegts @ 0x7fffc56a4c40] PES packet size mismatch
[tls @ 0x7fffc586f0c0] Error in the pull function.
[mpegts @ 0x7fffc56a4c40] PES packet size mismatch
[tls @ 0x7fffc5c3ce80] Error in the pull function.
[tls @ 0x7fffc5c3ce80] The specified session has been invalidated for some reason.
[hls @ 0x7fffc53ce440] keepalive request failed for 'https://edge281.stream.highwebmedia.com/live-edge/amlst:grettabenett-sd-cee28f684c6ae00bc31c053d29db8b3d492314d19d437f23bb8c52e99302e16a_trns_h264/media_w285279153_b5128000_t64RlBTOjMwLjA=_2828.ts' when opening url, retrying with new connection: Input/output error
[tls @ 0x7fffc586f0c0] The specified session has been invalidated for some reason.
[hls @ 0x7fffc53ce440] keepalive request failed for 'https://edge281.stream.highwebmedia.com/live-edge/amlst:grettabenett-sd-cee28f684c6ae00bc31c053d29db8b3d492314d19d437f23bb8c52e99302e16a_trns_h264/media_w285279153_b5128000_t64RlBTOjMwLjA=_2829.ts' when opening url, retrying with new connection: Input/output error
[mpegts @ 0x7fffc56a4c40] PES packet size mismatch
[tls @ 0x7fffc5afa380] Error in the pull function.
[tls @ 0x7fffc5afa380] The specified session has been invalidated for some reason.
[hls @ 0x7fffc53ce440] keepalive request failed for 'https://edge281.stream.highwebmedia.com/live-edge/amlst:grettabenett-sd-cee28f684c6ae00bc31c053d29db8b3d492314d19d437f23bb8c52e99302e16a_trns_h264/media_w285279153_b5128000_t64RlBTOjMwLjA=_2830.ts' when opening url, retrying with new connection: Input/output error


他就这样无限重复  
然后主播绝对在线上  我一边开着一边用的
我人不在中国大陆  跟这个会有关系吗

这是我的磁碟使用率
Filesystem     1K-blocks      Used Available Use% Mounted on
rootfs         498746364 221176040 277570324  45% /
none           498746364 221176040 277570324  45% /dev
none           498746364 221176040 277570324  45% /run
none           498746364 221176040 277570324  45% /run/lock
none           498746364 221176040 277570324  45% /run/shm
none           498746364 221176040 277570324  45% /run/user
tmpfs          498746364 221176040 277570324  45% /sys/fs/cgroup
C:\            498746364 221176040 277570324  45% /mnt/c
D:\            957054972 346927388 610127584  37% /mnt/d

**Comment by KFERMercer** [comment]
fixed
