### ISSUE TITLE
最近抓取下来的 ts 文件，都存在卡顿现象

### ISSUE THREAD

**Issue by Orenoid** [KFERMercer/chaturbate-grabber#5]
具体表现为播放时，每一两秒就卡一下，然后突然切到下一个画面，整个视频就像很多不连贯的小片段拼装成的。
不知道单纯是我网络问题，还是 CB 改了什么传输机制？请问大佬有什么排查和解决建议吗？

**Comment by KFERMercer** [comment]
日志发一下

**Comment by Orenoid** [comment]
录制了几分钟测试了下，还是有这个现象，日志如下。

[20220116-150612-jennycutey.log](https://github.com/KFERMercer/chaturbate-grabber/files/7876530/20220116-150612-jennycutey.log)

P.S. 该录制是通过指定节点的形式进行的，默认寻找网络节点一直 404
```
ctbcap <streamer> <节点数字>
```

**Comment by KFERMercer** [comment]
没能复现, 你可以试试在`ctbcap`的`82`行与`83`行之间加一行:
```shell
-flags +global_header \
```
看看能不能解决问题
